name: Collector
on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 3
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 3

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.3"
      - run: go version

      - name: Build and run Golang file
        run: |
          go build -o myapp
          ./myapp -sort -log warn
      
      - name: Speedtest
        run: |
          ./tool/speedTest_singtools/singtools test   -i ./results/mixed.txt -o ./results/mixed_tested.json -e fatal -f ""
      
      - name: Convert to mixed with base64encode
        run: |
          ./tool/subconverter/subconverter &
          
          until curl -s http://0.0.0.0:25500 >/dev/null; do
            sleep 1
          done

          # curl -o ./results/mixed_tested.txt http://0.0.0.0:25500/sub\?target\=mixed\&url\=./results/mixed_tested.json

          # 执行 curl 命令并将结果保存到文件，同时添加错误检查
          if ! curl -o ./results/mixed_tested.txt http://0.0.0.0:25500/sub\?target\=mixed\&url\=./results/mixed_tested.json; then
            echo "curl 请求失败，退出步骤"
            exit 1
          fi
          # 检查文件是否成功下载
          if [ ! -f "./results/mixed_tested.txt" ]; then
            echo "下载的文件未找到，退出步骤"
            exit 1
          fi

      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add ./results/*
          git checkout main
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
